[package]
name = "quickscript"
version = "0.1.0"
authors = ["Trig Northrup <northruptrig@gmail.com>"]
edition = "2024"
rust-version = "1.85"

[dependencies]
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
