[package]
name = "quickscript"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
actix-web = "4.11.0"
cranelift = "0.114.0"
cranelift-jit = "0.114.0"
cranelift-module = "0.114.0"
dashmap = "6.1.0"
fastrand = "2.3.0"
tokio = { version = "1.46.0", features = ["full"] }
cranelift-native = "0.114.0"
